// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmfY-sosvirDVhe_wMMYJ0MwcL0R91ubw',
    appId: '1:93995853083:web:df8d9719e7907c40361fbe',
    messagingSenderId: '93995853083',
    projectId: 'ads-chat2-ff42d',
    authDomain: 'ads-chat2-ff42d.firebaseapp.com',
    storageBucket: 'ads-chat2-ff42d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfkZq3yI0rNF7kNE96M_qwGSimWsGd8XI',
    appId: '1:93995853083:android:9a0d6075e38d30a5361fbe',
    messagingSenderId: '93995853083',
    projectId: 'ads-chat2-ff42d',
    storageBucket: 'ads-chat2-ff42d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBhiNo5FB0p9VQP1IFW-uppvf6IwqrwDY',
    appId: '1:93995853083:ios:79510b432a96e23f361fbe',
    messagingSenderId: '93995853083',
    projectId: 'ads-chat2-ff42d',
    storageBucket: 'ads-chat2-ff42d.appspot.com',
    iosClientId: '93995853083-3gi8qeihop0rj8ohtvsrv4tlffhtni5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.adsChat2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBhiNo5FB0p9VQP1IFW-uppvf6IwqrwDY',
    appId: '1:93995853083:ios:79510b432a96e23f361fbe',
    messagingSenderId: '93995853083',
    projectId: 'ads-chat2-ff42d',
    storageBucket: 'ads-chat2-ff42d.appspot.com',
    iosClientId: '93995853083-3gi8qeihop0rj8ohtvsrv4tlffhtni5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.adsChat2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmfY-sosvirDVhe_wMMYJ0MwcL0R91ubw',
    appId: '1:93995853083:web:f7df4a2aa673575d361fbe',
    messagingSenderId: '93995853083',
    projectId: 'ads-chat2-ff42d',
    authDomain: 'ads-chat2-ff42d.firebaseapp.com',
    storageBucket: 'ads-chat2-ff42d.appspot.com',
  );

}